### ISSUE TITLE
Why do whe have seperate const in app.module for registering components?

### ISSUE THREAD

**Issue by jaapjorisjaap** [UUDigitalHumanitieslab/gretel#105]
Now we have 'export const declarations = [....]'  instead of just declaring the components it in @NgModule.
This messes the ng g component command, en creates an error after a new component is created with that command.

**Comment by oktaal** [comment]
The exported `declarations` is used in the unit test for creating a test module:

https://github.com/UUDigitalHumanitieslab/gretel/blob/c214dacfbec6d7454a2578f3db8df8a16989f56d/web-ui/src/app/common-test-bed.ts#L69-L76

This way you won't need to redefine the module and its components when creating a test. Perhaps it could be possible to re-export from the `@NgModule` declaration somehow. Otherwise it could be done using reflection or some compile-time operation if all else fails. But for now I think it would be better to manually correct this on creation. I suppose a similar problem exists when a new service is added to the `providers`. At least that can be solved more elegantly in Angular 6 by using `providedIn`: https://blog.ninja-squad.com/2018/05/04/what-is-new-angular-6/#tree-shakeable-providers
